name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
      - 
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            touch message.txt
            echo "Successfully" >> message.txt
            sudo chmod 777 /var/run/docker.sock
            docker stop ${{ secrets.DOCKER_CONTAINER }}
            docker rm ${{ secrets.DOCKER_CONTAINER }}
            docker rmi ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}:latest
            docker run --name ${{ secrets.DOCKER_CONTAINER }} -p 80:8000 -d -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBNAME=${{ secrets.DBNAME }} -e DBPORT=${{ secrets.DBPORT }}  --link  ${{ secrets.DBHOST }} ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE }}